# Rayleigh documentation environment.
#
# If you change this file make sure to also update
# environment.yml.

name: radoc
channels:
  - conda-forge
dependencies:
  - python=3.9
  - matplotlib=3.4
  - jupyter=1.0
  - scipy=1.6
  - sphinx=4.0
  - sphinxcontrib-bibtex=2.2
  - nbsphinx=0.8
  - pandoc=2.13
  - recommonmark=0.7
  - funcsigs=1.0
  - vtk=9.0
