#!/bin/sh
mkdir Checkpoints
mkdir AZ_Avgs
mkdir G_Avgs
mkdir Shell_Avgs
mkdir Shell_Slices
mkdir Timings
mkdir Spherical_3D
mkdir Shell_Spectra
mkdir Benchmark_Reports
mkdir Equatorial_Slices
mkdir Meridional_Slices
mkdir SPH_Mode_Samples
mkdir Point_Probes
