ntheta = 128
nphi = 2*ntheta
spawn, 'ls workspace/*initial', ifiles
ni = N_ELEMENTS(ifiles)

cube = dblarr(nphi,100,ntheta,1)
for i = 0, ni -1 DO BEGIN
	read_4d,ifiles[i],dat, lims = lims
	rstart = lims.rstart
	rend = lims.rend
	tstart = lims.tstart
	tend = lims.tend
	cube[*,rstart:rend,tstart:tend,0] = dat
endfor

spawn, 'ls workspace/*post', ifiles
ni = N_ELEMENTS(ifiles)
cube2 = 0*cube

for i = 0, ni -1 DO BEGIN
	read_4d,ifiles[i],dat, lims = lims
	rstart = lims.rstart
	rend = lims.rend
	tstart = lims.tstart
	tend = lims.tend
	cube2[*,rstart:rend,tstart:tend,0] = dat
endfor


end
